### PR TITLE
Update to 1.17.0

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by pkgw** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
Well, that rerender didn't accomplish what I hoped. The problem seems to be that `.ci_support/win_64_.yaml` still calls for `m2w64-toolchain` as the compiler, rather than `gcc`. I guess I need to manually import the migration file.

**Comment by isuruf** [comment]
> Well, that rerender didn't accomplish what I hoped. The problem seems to be that .ci_support/win_64_.yaml still calls for m2w64-toolchain as the compiler, rather than gcc. I guess I need to manually import the migration file.

Yeah, the migrator was held up because `xcb-proto` was only built for 1.17.0 with the new compilers. Even after this PR is merged, it'll be held up unless we fix https://github.com/conda-forge/libxcb-feedstock/issues/20

**Comment by isuruf** [comment]
Yeah, should be good to go

**Pull request merged**
